### ISSUE TITLE
Setting table properties is really slow

### ISSUE THREAD

**Issue by bilalaslamseattle** [databricks/dbt-databricks#121]
### Describe the feature
Setting many table properties is slow (e.g. when you use them for column documentation) because when you set one table property, Hive Metastore rewrites all of them.

### Proposal
Enhance dbt-databricks to fetch all the comments, do a diff with what's in the dbt project and only issue updates if the diffs don't match.

### Who will this benefit?
Everyone! Faster table properties would be nice!

**Comment by benc-db** [comment]
For comments, we added a feature to selectively persist column comments based on diff from existing starting in 1.7.2.  We're waiting on support for bulk column update in alter table to really consider that issue fully addressed.  As far as tblproperties, part of the issue is knowing which ones were created by Databricks, and thus are unsafe to modify, AND also expected to be there (so don't count as a diff).  I'm working on something along these lines for materialized views / streaming tables.
