### ISSUE TITLE
Automatically start cluster for Python models

### ISSUE THREAD

**Issue by bilalaslamseattle** [databricks/dbt-databricks#232]
### Describe the feature
The context API won't automatically start a cluster today. `create_notebook` uses a different method which does automatically start a cluster. This could be solved in the dbt-databricks adapter by checking if the cluster is active and starting it if it isn't.

**Comment by boxysean** [comment]
Hi, I am experiencing this issue in my project. I understood your note to mean that, if I were to specify `create_notebook=True` in my `config()` block within my python model, then it would not start a cluster. However, I am now believing you mean that dbt python models are not able to auto-start a cluster because such execution creates a notebook, which requires a started cluster (and does not auto-start). Is that correct?

What do the solution look like? Which API call to the Databricks cluster -- do you envision a trigger and polling routine? Thanks!
