### ISSUE TITLE
Databricks write table should parameterize write mode and overwriteSchema to model config

### ISSUE THREAD

**Issue by ybressler** [databricks/dbt-databricks#416]
### Describe the feature
Currently, `databricks__py_write_table()` macro hardcodes the values for `write mode` as well as write option `overwriteSchema`. Instead, these values should be parsed via `py_get_writer_options()` from the `model config`.

**Current:**
```
writer = (
    df.write
        .mode("overwrite")
        .option("overwriteSchema", "true")
{{ py_get_writer_options()|indent(8, True) }}
)
```

**Proposed:**
```
writer = (
    df.write
{{ py_get_writer_options()|indent(8, True) }}
)


{%- macro py_get_writer_options() -%}
...
{%- set write_mode = config.get('mode', default='overwrite') -%}
{%- set overwrite_schema = config.get('overwriteSchema', default=True) -%}

.mode("{{ write_mode }}")
{% if overwrite_schema %}
.option("overwriteSchema", "true")
{% else %}
.option("mergeSchema", "true")
{% endif %}
...

{% endmacro -%}
```

Some nuance is needed for `overwriteSchema|mergeSchema`, but we can figure out preferred method for this.

### Describe alternatives you've considered
Alternative is to overwrite the `databricks__py_write_table()` macro entirely, using custom write mode + options. But this is not preferred.

### Additional context
None.

### Who will this benefit?
Developers using diverse write modes with databricks + dbt.

### Are you interested in contributing this feature?
Yup. Happy to contribute.

**Comment by benc-db** [comment]
@ybressler I will be making updates to docs around this, but the way dbt implements python models today, only some of the config options become part of the rendered notebook, and this in intentional.  It is because dbt's incremental python approach looks like this:

On first run or full refresh - make a notebook that makes the target table (here overwrite is correct, because the intent is to either make a new table or blow away an existing one for the full refresh)

On incremental runs - make a notebook that makes a staging table (here overwrite is fine because it is a staging table that is dropped after the run), then use a SQL command to merge that staging table into the target table.  The additional config is part of the merge command, and not expected to be present in the python notebook.

**Comment by ybressler** [comment]
Interesting. Thank you for the clarification. Please do update the documentation + provide references to the source code described. TY!

**Comment by benc-db** [comment]
Still need to update the documentation, but now the generated notebook indicates to users that they need to look in the dbt.log for the complete picture.  New source code is here: https://github.com/databricks/dbt-databricks/blob/main/dbt/include/databricks/macros/python.sql

 and here is the part where it operates using SQL https://github.com/databricks/dbt-databricks/blob/90aa99ca526ab9b29ad84dc39de9fa3c2f7610de/dbt/include/databricks/macros/materializations/incremental/incremental.sql#L52

Notice how regardless of whether we're using SQL or Python, we use build_sql as part of the merge call.
