### ISSUE TITLE
OAuth token caching fails in Docker/K8S

### ISSUE THREAD

**Issue by sithson** [databricks/dbt-databricks#553]
### Describe the bug
OAuth token caching fails in Docker/K8S.

### Steps To Reproduce
1. Setup dbt profile for U2M OAuth to Databricks
2. Start dbt Docker container and do ”dbt run”
3. In the web popup, authenticate yourself to Databricks
4. You will be authed
5. You will get error message for ”Cannot save auth token” and dbt run will continue as expected
6. On the next dbt run you will be informed ”Cannot load cached auth token” and you have to start over from step (3) again

### Expected behavior
After step (4) above, the OAuth token will be cached for subsequent dbt runs without the need to re-auth within the token lifetime.

### Screenshots and log output
```
root@e074d3d1b4e7:/app/dbt# dbt run
Found 666 models, 42 tests, 18 sources, 0 exposures, 0 metrics, 923 macros, 0 groups, 0 semantic models
Databricks adapter: could not retrieved saved token
Databricks adapter: could not save token
```

### System information
**The output of `dbt --version`:**
```
root@e074d3d1b4e7:/app/dbt# dbt --version
Core:
  - installed: 1.7.4
  - latest:    1.7.4 - Up to date!

Plugins:
  - duckdb:     1.7.1 - Up to date!
  - databricks: 1.7.3 - Up to date!
  - spark:      1.7.1 - Up to date!
```

**The operating system you're using:**
- Windows 10
- Docker image with Ubuntu v22.04

**The output of `python --version`:**
- Python 3.10.12

**Comment by benc-db** [comment]
@andrefurlan-db do you have any context?  I would not have expected the token to be cached between run, but the output here does suggest that it is a planned behavior.

**Comment by sithson** [comment]
Is the planned behaviour to store the token?

**Comment by sithson** [comment]
The context:
- Subsequent dnt runs by the the engineer without having to auth after each dbt run

**Comment by benc-db** [comment]
Talked to Andre offline, he suggested following the steps [here](https://pypi.org/project/keyring/) for 'Using Keyring on headless Linux systems in a Docker container' could help.

**Comment by thijs-nijhuis-shell** [comment]
I ran into the same issue yesterday when running with VS Code on my windows 11 laptop. Every time I run compile, a new browser tab is opened. Two even because I have a profile for the elementary package in there as well. This makes the development experience so poor that I switched back to hardcoding the token (which I was hoping to avoid because of security reasons). 

To debug it, I changed my local code slightly to log the exception as info instead of debug ([line 411](https://github.com/databricks/dbt-databricks/blob/main/dbt/adapters/databricks/connections.py#L411)) and than right before the 'Databricks adapter: could not save token' message I get this one: Databricks adapter: (1783, 'CredWrite', 'The stub received bad data') .

I think it is related to this issue in keyring: https://github.com/jaraco/keyring/pull/544 . There is says that windows has a limit of storing 1.280 (utf-16) characters and that storing the entire jwt token can easily go over that limit. In fact, the token I got returned is 2.887 characters long. Here is a similar issue in poetry that is tracked back to keyring with the same reason: https://github.com/python-poetry/poetry/issues/6597 .

I checked and on my laptop keyring 24.3.0 is installed which is the latest.

Not sure if this is the same issue or something completely different. More than happy to create a new issue if it is something different of course.

**Comment by sithson** [comment]
Thx benc! Will check if it fits us, and if it works.

> Talked to Andre offline, he suggested following the steps [here](https://pypi.org/project/keyring/) for 'Using Keyring on headless Linux systems in a Docker container' could help.

**Comment by thijs-nijhuis-shell** [comment]
FYI, I have remove my comment on a similar issue on windows 11 as that seems to have a different reason and I didn't want to block closing this one. I created a new issue for the windows 11 here: https://github.com/databricks/dbt-databricks/issues/563
