### ISSUE TITLE
Not all columns populated on column addition

### ISSUE THREAD

**Issue by JamesYouL2** [databricks/dbt-databricks#594]
### Describe the bug
Rerunning dbt run with changed columns leads to dropped columns.

### Steps To Reproduce
Change schema of table (add new column) and rerun table only populates a limited set of columns.
old table1:
a
b
d

Adding new column:
c

D doesn't get populated.

### Expected behavior
All columns populated in new table.

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.7.8
  - latest:    1.7.8 - Up to date!

Plugins:
  - databricks: 1.7.8 - Up to date!
  - spark:      1.7.1 - Up to date!
```

**The operating system you're using:**

**The output of `python --version`:**
Python 3.11.4

### Additional context

**Comment by benc-db** [comment]
Can you provide more details...specifically, when you say you added a column, did your SQL change, your schema.yml, or both?  Do you see the same behavior with 1.7.7?

**Comment by benc-db** [comment]
What is your on_schema_change set to?  Note, per https://docs.getdbt.com/docs/build/incremental-models#default-behavior, if you have not expressly set an on_schema_change, the expected behavior is actually to keep d and not add c, which is surprising to me.

**Comment by JamesYouL2** [comment]
1. My SQL changed.
2. And the on_schema_change is set to sync_all_columns. I think it also breaks if it is set to append_new_columns as well. 

I have not tested with 1.7.7. I do not see this behavior with 1.6.4. And this bug doesn't happen if I run --full-refresh/recreate the table.

**Comment by benc-db** [comment]
1.7.8 specifically has a change that I'm concerned about, so if you could validate with 1.7.7 I would appreciate it.  Thanks for filing the bug.

**Comment by JamesYouL2** [comment]
1.7.7 works fine and did not break.

**Comment by benc-db** [comment]
@case-k-git looks a regression introduced by your change.  Would love if you could help debug, but understand if you can't.

**Comment by benc-db** [comment]
@JamesYouL2 for now, I recommend 1.7.7 if it works for you.  I will try to get another patch of 1.7.x in the next week or so to fix this and any other small things that come up, but otherwise I'm heads down on 1.8.0 compat work.  Apologies that our tests didn't catch this, will add a ticket to my backlog for that.

**Comment by case-k-git** [comment]
Sure. let me check it.

**Comment by case-k-git** [comment]
Hi @JamesYouL2 
Let me check more detail. Have you tired is under the way?

Step 1: Create the under column model
a
b
d

Step 2 Adding new column(c) and remove column(d):
a
b
c

Step 3 Rerun and confirm column d is dropped
a
b
c

Could you please let me check if my understanding is correct?
I have checked documentation and drop columns seems to be expected behavior.

>sync_all_columns: Adds any new columns to the existing table, and removes any columns that are now missing. Note that this is inclusive of data type changes. On BigQuery, changing column types requires a full [table](https://docs.getdbt.com/terms/table) scan; be mindful of the trade-offs when implementing.

https://docs.getdbt.com/docs/build/incremental-models#what-if-the-columns-of-my-incremental-model-change

**Comment by case-k-git** [comment]
I have checked but could not confirm it. This is the step what I did.

@JamesYouL2  Could you please let me know more detail how did you confirm it? I will test it.

Step1:  Execute under the SQL(only id columns)
```
{ config(
    materialized='incremental',
    incremental_strategy='append',
    on_schema_change='sync_all_columns',
    tags=["daily"]
) }}

select id, date from {{ ref('daily_model') }}
```

Step2:  Add the date column
```
{ config(
    materialized='incremental',
    incremental_strategy='append',
    on_schema_change='sync_all_columns',
    tags=["daily"]
) }}

select id, date from {{ ref('daily_model') }}
```

Step 3: Confirm New columns is added as expected
<img width="192" alt="image" src="https://github.com/databricks/dbt-databricks/assets/40357957/e38530dd-e4c7-41c5-a1cb-eafe1c6fc1c8">


Logs
````
dbt --version
Core:
  - installed: 1.7.8
  - latest:    1.7.8 - Up to date!

Plugins:
  - databricks: 1.7.8 - Up to date!
  - spark:      1.7.1 - Up to date!


dbt run       
09:31:21  Running with dbt=1.7.8
09:31:22  Registered adapter: databricks=1.7.8
09:31:22  Found 2 models, 1 source, 0 exposures, 0 metrics, 535 macros, 0 groups, 0 semantic models
09:31:22  
09:31:24  Concurrency: 1 threads (target='dev')
09:31:24  
09:31:24  1 of 2 START sql table model schema_demo.daily_model ........................... [RUN]
09:31:27  1 of 2 OK created sql table model schema_demo.daily_model ...................... [OK in 3.11s]
09:31:27  2 of 2 START sql incremental model schema_demo.daily_model_2 ................... [RUN]
09:31:32  2 of 2 OK created sql incremental model schema_demo.daily_model_2 .............. [OK in 5.36s]
09:31:33  
```

**Comment by benc-db** [comment]
@case-k-git  Yeah, sync_all_columns only could do something meaningfully different from append on certain non-Delta formats (for now; there is a feature in preview right now that will allow 'dropping' columns by hiding them).  So if column d is going away, I think one of 3 things must be true:

1. This is happening on a format that supports column drop (not sure if this is even possible in Databricks, but I haven't ruled it out).
2. Column d is getting renamed to c; I think this might be one of those cases where Databricks does a merge by order rather than by name.
3. Something else very weird is happening in the merge statement

@JamesYouL2 if you could either share a redacted version of the merge statement from your dbt.log when running with 1.7.7 and 1.7.8, or file a ticket with Databricks with the complete log, that could probably speed up diagnosing the issue.

**Comment by lachniej** [comment]
@benc-db we are having the same issue since exactly the time of the version upgrade to v1.7.8 with the same configuration scenario as @case-k-git except that our model build is not failing, it is just not writing any data to the destination tables. We have not had any schema changes to our model either. We are reverting back to 1.7.7 to see if that resolves the issue.

**Comment by case-k-git** [comment]
@lachniej 
Thank you for sharing. So previously you have 25 redacted columns but now you only have row_hash columns.
Does your SQL model also have 25 redacted column? or just row_hash column?

I want to check the columns of this statement 「tl.*」you shared
```
SELECT tl.*
FROM `****`.`****`.`****` tl

  LEFT ANTI JOIN hash_cte hcte ON **.row_hash = **.row_hash
```

**Comment by case-k-git** [comment]
if  SQL model statement 「tl.*」 still have 25 columns and only insert row_hash column, It must be bug. But if  SQL model statement 「tl.*」have only contain `row_hash` column  and insert `row_hash ` only it is the expected dbt behavior which is solved by  v1.7.8

dbt document
>sync_all_columns: Adds any new columns to the existing table, and removes any columns that are now missing. Note that this is inclusive of data type changes. On BigQuery, changing column types requires a full [table](https://docs.getdbt.com/terms/table) scan; be mindful of the trade-offs when implementing

https://docs.getdbt.com/docs/build/incremental-models

**Comment by case-k-git** [comment]
Hello @benc-db 
I have tired but still can not reproduction environment.
When I think about my change, I think drop column will not happen. but as  @lachniej mention, does not write the record could be happen.Because of checking column match of source and target table.
But as I share tested, I can not reproduction environment(including lower, upper..etc).

**Comment by benc-db** [comment]
Thanks for investigating @case-k-git.  I'll try to puzzle it out after getting the incremental functional tests that we're missing for this scenario.

**Comment by benc-db** [comment]
@case-k-git I believe the issue is this from the INSERT page:

```
query -
A query that produces the rows to be inserted.

You must match the number of columns returned by the query with the specified or implied insert column list.
```

**Comment by benc-db** [comment]
This is different from if we were using BY NAME, which I do want to get working at some point, but since it only works with newer DBRs, I haven't gotten around to it.

**Comment by benc-db** [comment]
Hi all, please checkout if this PR fixes your issues: https://github.com/databricks/dbt-databricks/pull/604

I intend to release today or tomorrow, but would appreciate if anyone could validate the change beforehand.

@case-k-git to deal with the mismatched column issue, for anything in source where there is a non-matching column, I'm setting to NULL.  I believe this is the same behavior we would see if we set the tables to evolve schemas, and I will probably look at that sometime in 1.8.x, but this approach I think is more backwards compat.  Would love you to take a look at the PR.

**Comment by case-k-git** [comment]
Thank you @benc-db 

We also got the comment here 
https://github.com/databricks/dbt-databricks/pull/580#discussion_r1512091497

**Comment by case-k-git** [comment]
Yea I confirm this  error is caused by columns change order.

After Eeecute 2 times of model_b, change the column order of mode_b from「id ,date」to 「date, id」then null was inserted. Probably, If we did not user single loop to check columns match of source and target we will be able to fix this as he mention.

<img width="206" alt="error" src="https://github.com/databricks/dbt-databricks/assets/40357957/2845d74e-c953-4c2b-81a1-e45c368816d4">


**Sample**
model_a
```
{{ config(
    materialized='table',
    ) }}

with source_data as (

    select 1 as id , '2023-11-01' as date
    union all
    select 2 as id , '2023-11-02' as date
    union all
    select 3 as id , '2023-11-03' as date
)

select *
from source_data
```

model_b
```
{{ config(
    materialized='incremental',
    incremental_strategy='append',
    on_schema_change='sync_all_columns',
    tags=["daily"]
) }}


select id, date from {{ ref('model_a') }}
```

**Comment by benc-db** [comment]
Yes, I was generally hitting an issue with enumeration due to jinja producing a generator, so in my PR I've been converting them to lists.  Does my current PR have any issues?  Would I be able to validate by swapping the order of columns in my tests?

**Comment by case-k-git** [comment]
@benc-db  Thank you for solving the issue!!

**Comment by nimeshpatni** [comment]
> Yes, I was generally hitting an issue with enumeration due to jinja producing a generator, so in my PR I've been converting them to lists. Does my current PR have any issues? Would I be able to validate by swapping the order of columns in my tests?

Hi, Thank you for solving this, but changes might raise another issue, could you please [take a look](https://github.com/databricks/dbt-databricks/pull/604/files#r1513862137). Thanks
